DROP SEQUENCE BOARDNOSQ;
DROP SEQUENCE GROUPNOSQ;
DROP TABLE ANSWERBOARD;

--글 번호 시퀀스(PRIMARY KEY, 모든 글과 댓글마다 부여)
CREATE SEQUENCE BOARDNOSQ NOCACHE;

--그룹 번호 시퀀스(새로운 글에만 부여)
CREATE SEQUENCE GROUPNOSQ NOCACHE;

CREATE TABLE ANSWERBOARD(
	BOARDNO NUMBER PRIMARY KEY,  	--글번호
	GROUPNO NUMBER NOT NULL,		--그룹 번호, 새로운 글 작성시에만 부여
	GROUPSQ NUMBER NOT NULL,		--같은 그룹 안에서의 순서
	TITLETAB NUMBER NOT NULL,		--새로운 글 아래 답글인지,답글의 답글인지 확인하고 공간을 주기위한 탭
	TITLE VARCHAR2(2000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	WRITER VARCHAR2(1000) NOT NULL,
	REGDATE DATE NOT NULL
);

--첫번째 글
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSQ.NEXTVAL,GROUPNOSQ.NEXTVAL,1,0,'첫번째 글','1번 글입니다','유저1',SYSDATE);

--두번째 글
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSQ.NEXTVAL,GROUPNOSQ.NEXTVAL,1,0,'두번째 글','2번 글입니다','유저2',SYSDATE);

--답글 작성(1번글에)
--부모와 같은 GROUPNO
--부모의 GROUPSQ+1, 부모의 TITLETAB+1
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSQ.NEXTVAL,
	(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=1),
	(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=1)+1,
	(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=1)+1,
	'RE:첫번째 글','1번글에 답글입니다.','유저2',SYSDATE);

SELECT * FROM ANSWERBOARD ORDER BY GROUPNO DESC, GROUPSQ;

--세번째 글 작성
INSERT INTO ANSWERBOARD
VALUES (BOARDNOSQ.NEXTVAL, GROUPNOSQ.NEXTVAL, 1,0,'세번째 글','3번 글입니다','유저3',SYSDATE);

--답글 작성(2번글에)
--부모와 같은 GROUPNO
--부모의 GROUPSQ+1, 부모의 TITLETAB+1
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSQ.NEXTVAL,
	(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=2),
	(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=2)+1,
	(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=2)+1,
	'RE:두번째 글','2번글에 답글입니다.(1)','유저1',SYSDATE
);
	
SELECT * FROM ANSWERBOARD
ORDER BY GROUPNO DESC, GROUPSQ;

--답글 작성(RE:두번째 글 NO=5)
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSQ.NEXTVAL,
	(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=5),
	(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=5)+1,
	(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=5)+1,
	'RE:RE:두번째 글','2Q번글 답글에 답글','유저2',SYSDATE
);
	
--답글 작성 (두번째 글 NO=2)
--부모와 같은 GROUPNO에서
--부모의 GROUPSQ보다 큰 글들의 GROUPSQ + 1

--답글의 순서를 맞추기 위해 이전값들을 1씩 증가하여 들어갈 자리를 만듬
UPDATE ANSWERBOARD SET GROUPSQ= GROUPSQ+1
WHERE GROUPNO = (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=2)
  AND GROUPSQ > (SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=2);
 
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSQ.NEXTVAL,
	(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=2),
	(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=2)+1,
	(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=2)+1,
	'RE:두번째 글','2번글에 답글입니다(2)','유저2',SYSDATE
);

--답변작성 (RE:두번째글 NO=7)
--부모와 같은 GROUPNO 에서
--부모의 GROUPSQ보다 큰 글들의 GROUPSQ+1

UPDATE ANSWERBOARD SET GROUPSQ=GROUPSQ+1
WHERE GROUPNO=(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=7)
AND GROUPSQ>(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=7);

INSERT INTO ANSWERBOARD
VALUES(BOARDNOSQ.NEXTVAL,
	(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=7),
	(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=7)+1,
	(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=7)+1,
	'RE:RE:두번째 글','2번글에 답글입니다(2)','유저2',SYSDATE
);

SELECT * FROM ANSWERBOARD
ORDER BY GROUPNO DESC, GROUPSQ;
