CREATE SEQUENCE MYSEQ NOCACHE;
CREATE TABLE MYBOARD(
	MYNO NUMBER PRIMARY KEY,
	MYNAME VARCHAR2(100) NOT NULL,
	MYTITLE VARCHAR2(1000) NOT NULL,
	MYCONTENT VARCHAR2(4000) NOT NULL,
	MYDATE DATE NOT NULL
);

INSERT INTO MYBOARD 
VALUES(MYSEQ.NEXTVAL, '관리자','게시판테스트','테스트중입니다12345678ABCDEF',SYSDATE);

SELECT * FROM MYBOARD;