CREATE SEQUENCE INUM START WITH 1001;
DROP TABLE ICONBOARD;
CREATE TABLE ICONBOARD(
	I_NO NUMBER(8) PRIMARY KEY,
	I_IMG VARCHAR2(3000),
	I_NAME VARCHAR2(100) NOT NULL,
	I_DESIGNER VARCHAR2(500) NOT NULL,
	I_DESCRIPT VARCHAR2(3000) NOT NULL,
	I_PRICE VARCHAR2(20) NOT NULL,
	I_DATE VARCHAR2(500) NOT NULL
);
INSERT INTO ICONBOARD
VALUES (INUM.NEXTVAL,'https://image.flaticon.com/icons/png/512/731/731985.png','Apple','fruit kim','검은사과','15000',SYSDATE);

SELECT * FROM ICONBOARD;